repos:
  # Quick hygiene checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: debug-statements

  # isort (imports) – run before Black
  - repo: https://github.com/PyCQA/isort
    rev: 6.0.1
    hooks:
      - id: isort
        additional_dependencies: ["toml"]  # to read pyproject.toml
        args: ["--filter-files"]

  # Black (formatter)
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black

  # Flake8 (lint)
  - repo: https://github.com/pycqa/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear==24.4.26
          - flake8-comprehensions==3.15.0
          - flake8-bandit==4.1.1
